/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author cruzr
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel_UsuarioActivo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton_Usuarios_ADMIN = new javax.swing.JButton();
        jButton_CerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel1.setText("Usuario Activo: ");
        jToolBar1.add(jLabel1);

        jLabel_UsuarioActivo.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel_UsuarioActivo.setMaximumSize(new java.awt.Dimension(300, 20));
        jLabel_UsuarioActivo.setMinimumSize(new java.awt.Dimension(200, 20));
        jLabel_UsuarioActivo.setPreferredSize(new java.awt.Dimension(200, 20));
        jToolBar1.add(jLabel_UsuarioActivo);

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/venta.png"))); // NOI18N
        jButton1.setMnemonic('V');
        jButton1.setText("Iniciar Venta (ALT+V)");
        jButton1.setToolTipText("Iniciar Venta");
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        jButton_Usuarios_ADMIN.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton_Usuarios_ADMIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sin título-2.png"))); // NOI18N
        jButton_Usuarios_ADMIN.setMnemonic('U');
        jButton_Usuarios_ADMIN.setText("Usuarios (ALT+U)");
        jButton_Usuarios_ADMIN.setToolTipText("Opciones De Usuarios");
        jButton_Usuarios_ADMIN.setBorderPainted(false);
        jButton_Usuarios_ADMIN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Usuarios_ADMIN.setFocusable(false);
        jButton_Usuarios_ADMIN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_Usuarios_ADMIN.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton_Usuarios_ADMIN);

        jButton_CerrarSesion.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton_CerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/configuracion.png"))); // NOI18N
        jButton_CerrarSesion.setMnemonic('S');
        jButton_CerrarSesion.setText("Cerrar Sesion (ALT+S)");
        jButton_CerrarSesion.setToolTipText("Cerrar Sesion De Usuario");
        jButton_CerrarSesion.setBorderPainted(false);
        jButton_CerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_CerrarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_CerrarSesion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton_CerrarSesion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 419, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    public javax.swing.JButton jButton_CerrarSesion;
    public javax.swing.JButton jButton_Usuarios_ADMIN;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel_UsuarioActivo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
